name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: go test -v github.com/alessandrobessi/piecetable/pkg/piecetable/
